[package]
name = "MTGA_me"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "wingdi", "shellscalingapi"] }
chrono = "0.4.40"
screenshot = "0.0.7"
image = "0.25.5"
nix = "0.29"
imageproc = "0.25"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"